version: '2'

services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  client:
    build:
      context: client
    depends_on:
      - 'server'
    ports:
      - '3000:3000'
    volumes:
      - './client:/app'
  server:
    build:
      context: server
    ports:
      - '8080:8080'
    volumes:
      - './server:/app'
    depends_on:
      - 'mongo'
    links:
      - 'mongo'

